---
name: Main branch continuous integration and snapshots deployment
on:
  push:
    branches:
      - "main"

concurrency:
  group: "ci-cd-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  snapshot:
    name: Deploy snapshots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Build with Maven
        run: ./mvnw --no-transfer-progress -s .build/maven-ci-settings.xml -B clean verify
      - name: Deploy snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECRET_FILES_PASSPHRASE: ${{ secrets.SECRET_FILES_PASSPHRASE }}
        run: just -f .build/justfile-for-release -d . deploy-to-maven-central
